; ============================================================
;  DaVinci Paddle Boat — Phase 0 (bring-up)
;  Board: Maker-ESP32-Pro (ESP32-WROOM-32E) -> generic esp32dev target
; ============================================================
[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200          ; serial baud (must match Serial.begin below)
build_flags   = -DCORE_DEBUG_LEVEL=1
